#! /bin/sh

. $(dirname $0)/modbus2mqtt.sh

topic="$1"
[ -z "${topic}" ] && usage "$0 <topic>"

# GPS
payload=""
payload=$(add_payload "${payload}" timestamp 365 2 32bit_uint1234)
payload=$(add_payload "${payload}" latitude 144 2 32bit_float1234)
payload=$(add_payload "${payload}" longitude 146 2 32bit_float1234)
payload=$(add_payload "${payload}" fix_time 148 16 ascii)
payload=$(add_payload "${payload}" date_time 164 16 ascii)
payload=$(add_payload "${payload}" speed 180 2 32bit_float1234)
payload=$(add_payload "${payload}" sat_count 182 2 32bit_uint1234)
payload=$(add_payload "${payload}" accuracy 184 2 32bit_float1234)
mqtt_pub "${topic}" "${payload}"

