#! /bin/sh
. $(dirname $0)/modbus2mqtt.sh

topic="$1"
[ -z "${topic}" ] && usage "$0 <topic>"

# SYSTEM sensors
payload=""
payload=$(add_payload "${payload}" uptime 1 2 32bit_uint1234)
payload=$(add_payload "${payload}" mobile_signal_strength 3 2 32bit_int1234)
payload=$(add_payload "${payload}" temperature 5 2 temp)
mqtt_pub "${topic}" "${payload}"
