#! /bin/sh
. $(dirname $0)/modbus2mqtt.sh

topic="$1"
[ -z "${topic}" ] && usage "$0 <topic>"

# SYSTEM data
payload=""
payload=$(add_payload "${payload}" hostname 8 16 ascii)
payload=$(add_payload "${payload}" operator 24 16 operator)
payload=$(add_payload "${payload}" serial_number 40 16 ascii)
payload=$(add_payload "${payload}" mac_address 56 16 ascii)
payload=$(add_payload "${payload}" router_name 72 16 ascii)
payload=$(add_payload "${payload}" sim_slot 88 16 ascii)
payload=$(add_payload "${payload}" net_reg_info 104 16 ascii)
payload=$(add_payload "${payload}" net_type 120 16 ascii)
payload=$(add_payload "${payload}" wan_ip 140 2 ip)
mqtt_pub "${topic}" "${payload}"
